name: deploy

on:
  push:
    branches:
      - backend

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push docker
        run: |
          DOCKER_NAME=requests_api-app
          DOCKER_IMAGE=docker.pkg.github.com/provodnicc/${GITHUB_REPOSITORY##*/}/${DOCKER_NAME}:backend
          

          docker tag ${{ matrix.name }} $DOCKER_IMAGE
          docker build -f Dockerfile --pull -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE